// Real Supabase (production project) regression tests for undo storage + recurring deletion. Uses only the public publishable key + throwaway users.
import { createClient } from '@supabase/supabase-js';
import { G, T, step, done, manila } from './lib.mjs';
process.env.SUITE = 'db';
const url = process.env.SUPABASE_URL, key = process.env.SUPABASE_PUBLISHABLE_KEY, stamp = Date.now();
const mk = () => createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
async function user(tag) { const c = mk(), { data, error } = await c.auth.signUp({ email: `pera-qa-${stamp}-db${tag}@example.com`, password: `Qa-${stamp}-pw!` }); if (error || !data.session) throw new Error('signUp failed: ' + (error?.message || 'no session')); return { c, id: data.user.id }; }
const A = await user('a'), B = await user('b');
const acc = (await A.c.from('accounts').select('id,name')).data, cats = (await A.c.from('categories').select('id,name,type')).data;
const cash = acc.find(a => a.name === 'Cash').id, util = cats.find(c => c.name === 'Utilities').id, food = cats.find(c => c.name === 'Food').id;
const today = manila(), [Y, M] = today.split('-').map(Number); const startOf = n => { let y = Y, m = M - n; while (m < 1) { m += 12; y--; } return `${y}-${String(m).padStart(2, '0')}-01`; };
const count = async q => (await q).count;
const txs = async desc => (await A.c.from('transactions').select('id,transaction_date,recurring_id').eq('description', desc).order('transaction_date')).data ?? [];

G('undo storage (tx_trash) — real database');
let t1;
await step('deleting a transaction archives a full copy in tx_trash (DB trigger)', async () => {
  const ins = await A.c.from('transactions').insert({ user_id: A.id, type: 'expense', category_id: food, account_id: cash, amount_minor: 12345, transaction_date: today, description: 'trash me' }).select('*').single(); if (ins.error) return ins.error.message; t1 = ins.data;
  const del = await A.c.from('transactions').delete().eq('id', t1.id); if (del.error) return del.error.message;
  const tr = await A.c.from('tx_trash').select('*').eq('tx_id', t1.id); return tr.data?.length === 1 && tr.data[0].row.amount_minor === 12345 && tr.data[0].row.description === 'trash me' ? true : tr.error?.message ?? tr.data; });
await step('the archived row can be restored with the same id and amount', async () => { const row = (await A.c.from('tx_trash').select('row').eq('tx_id', t1.id).single()).data.row; const { id, user_id, type, category_id, account_id, amount_minor, transaction_date, description } = row; const r = await A.c.from('transactions').insert({ id, user_id, type, category_id, account_id, amount_minor, transaction_date, description }).select('id'); return !r.error && r.data[0].id === t1.id ? true : r.error?.message; });
await step("another user cannot read or modify my trash", async () => { const r = await B.c.from('tx_trash').select('id').eq('user_id', A.id), d = await B.c.from('tx_trash').delete().eq('user_id', A.id).select('id'); return (r.data ?? []).length === 0 && (d.data ?? []).length === 0 ? true : { r: r.data, d: d.data }; });
await step('anonymous cannot read tx_trash or execute the trigger function', async () => { const a = mk(); const r = await a.from('tx_trash').select('id').limit(1); const f = await a.rpc('on_tx_delete'); return (r.data ?? []).length === 0 && f.error ? true : { r, f: f.error }; });
await step("another user's delete trigger never writes into my trash", async () => { const n0 = (await A.c.from('tx_trash').select('id', { count: 'exact', head: true })).count; const ins = await B.c.from('transactions').insert({ user_id: B.id, type: 'expense', category_id: (await B.c.from('categories').select('id').eq('name', 'Food').single()).data.id, account_id: (await B.c.from('accounts').select('id').eq('name', 'Cash').single()).data.id, amount_minor: 100, transaction_date: today }).select('id').single(); await B.c.from('transactions').delete().eq('id', ins.data.id); const n1 = (await A.c.from('tx_trash').select('id', { count: 'exact', head: true })).count; return n0 === n1 ? true : { n0, n1 }; });

G('recurring deletion — real database');
const rule = (o) => ({ user_id: A.id, account_id: cash, category_id: util, type: 'expense', amount_minor: 50000, description: 'DB Rent', interval_count: 1, frequency: 'monthly', start_date: startOf(2), next_run_date: startOf(2), ...o });
let rid;
await step('monthly rule starting 2 months ago generates exactly 3 occurrences', async () => { const r = await A.c.from('recurring_transactions').insert(rule()).select('id').single(); if (r.error) return r.error.message; rid = r.data.id; const rr = await A.c.rpc('run_recurring', { p_today: today }); if (rr.error) return rr.error.message; const t = await txs('DB Rent'); return t.length === 3 && t.every(x => x.recurring_id === rid) ? true : t.length; });
await step('running again is idempotent (no duplicates)', async () => { await A.c.rpc('run_recurring', { p_today: today }); return (await txs('DB Rent')).length === 3 ? true : (await txs('DB Rent')).length; });
let gone;
await step('deleting a generated occurrence does NOT bring it back on the next run', async () => { const t = await txs('DB Rent'); gone = t[1]; const d = await A.c.from('transactions').delete().eq('id', gone.id); if (d.error) return d.error.message; for (let i = 0; i < 3; i++) await A.c.rpc('run_recurring', { p_today: today }); const after = await txs('DB Rent'); return after.length === 2 && !after.some(x => x.transaction_date === gone.transaction_date) ? true : after; });
await step('the deleted occurrence is archived and restorable, and a later run does not duplicate it', async () => { const row = (await A.c.from('tx_trash').select('row').eq('tx_id', gone.id).single()).data?.row; if (!row) return 'not archived'; const { id, user_id, type, category_id, account_id, amount_minor, transaction_date, description, recurring_id } = row; const r = await A.c.from('transactions').insert({ id, user_id, type, category_id, account_id, amount_minor, transaction_date, description, recurring_id }); await A.c.rpc('run_recurring', { p_today: today }); return !r.error && (await txs('DB Rent')).length === 3 ? true : r.error?.message ?? (await txs('DB Rent')).length; });
await step('future occurrences continue: a later "today" adds the next month only', async () => { const future = new Date(Date.now() + 40 * 864e5).toISOString().slice(0, 10); const before = (await txs('DB Rent')).length; const rr = await A.c.rpc('run_recurring', { p_today: future }); const after = await txs('DB Rent'); return !rr.error && after.length >= before + 1 && new Set(after.map(x => x.transaction_date)).size === after.length ? true : { before, after: after.length, e: rr.error?.message }; });
await step('deleting the rule succeeds and preserves every past transaction', async () => { const before = (await txs('DB Rent')).length; const d = await A.c.from('recurring_transactions').delete().eq('id', rid).select('id'); if (d.error) return d.error.message; const after = await txs('DB Rent'); return d.data.length === 1 && after.length === before && after.every(x => x.recurring_id === null) ? true : { before, after: after.length, d: d.data }; });
await step("a deleted rule's old occurrence can still be deleted and restored", async () => { const t = await txs('DB Rent'); const d = await A.c.from('transactions').delete().eq('id', t[0].id); const row = (await A.c.from('tx_trash').select('row').eq('tx_id', t[0].id).single()).data?.row; return !d.error && row?.amount_minor === 50000 ? true : d.error?.message; });
await step('month-end rule (Jan 31 start) keeps no-drift dates', async () => { const r = await A.c.from('recurring_transactions').insert(rule({ description: 'DB EOM', start_date: '2025-01-31', next_run_date: '2025-01-31' })).select('id').single(); await A.c.rpc('run_recurring', { p_today: '2025-05-31' }); const d = (await txs('DB EOM')).map(x => x.transaction_date); return JSON.stringify(d) === JSON.stringify(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31']) ? true : d; });
await step('leap-day yearly rule: Feb 29 -> Feb 28 in non-leap years, back to Feb 29 in 2028', async () => { await A.c.from('recurring_transactions').insert(rule({ description: 'DB Leap', frequency: 'yearly', start_date: '2024-02-29', next_run_date: '2024-02-29' })); await A.c.rpc('run_recurring', { p_today: '2028-03-01' }); const d = (await txs('DB Leap')).map(x => x.transaction_date); return JSON.stringify(d) === JSON.stringify(['2024-02-29', '2025-02-28', '2026-02-28', '2027-02-28', '2028-02-29']) ? true : d; });
await step("another user's run_recurring never touches my rules", async () => { const n = (await txs('DB EOM')).length; await B.c.rpc('run_recurring', { p_today: '2030-01-01' }); return (await txs('DB EOM')).length === n ? true : 'changed'; });
// cleanup (data only; auth users remain)
for (const u of [A, B]) for (const t of ['transactions', 'recurring_transactions', 'budgets']) await u.c.from(t).delete().eq('user_id', u.id);
const out = done({ users: [`pera-qa-${stamp}-dba@example.com`, `pera-qa-${stamp}-dbb@example.com`] }); process.exit(out.fail ? 1 : 0);
